### ISSUE TITLE
Implicit client transform combinator, ~, does not work

### ISSUE THREAD

**Issue by fooblahblah** [jdegoes/blueeyes#1]
Chained combinators using ~ implicit do not execute.

In the example below, fail("blah") in the chained post$ call does not execute (nor do simple println calls). 

```
"GET /ads should return a JArray containing all adId's" in {
  path$("/ads") {
    post$(JValueToByteArray(adObject)) { response =>
      response.status.code mustEqual(OK)
    } ~
    post$(JValueToByteArray(JObject(JField("adId", JString("test-" + System.currentTimeMillis)) ::  Nil))) { response =>
      fail("blah") // never called!
      response.status.code mustEqual(OK)
    } ~
    get$ { response =>
      response.status.code mustEqual(OK)
      val jVal = ByteArrayToJValue(response.content.getOrElse[Array[Byte]](Array[Byte]())).asInstanceOf[JArray]
      jVal.values.length must be(2)
    } 
  } should "return a JArray containing all adId's"
}
```

**Comment by fooblahblah** [comment]
Note, this is in the context of a test Specification

**Comment by jdegoes** [comment]
The first error will kill the others. Unfortunately this behavior cannot be prevented because the combinators return a future of the response; e.g. if you join c1 which produces T, and c2 which produces S, then upon execution you'll get back a Future of (T, S). Thus, if any inner request fails to return a value, a dead future will be returned and other requests will not be executed.

**Comment by fooblahblah** [comment]
I was not clear in my example.  The fail never gets triggered.  The problem is the second post$, after ~, never gets called; neither does the get$, thus fail or anything else in the block do not get called.

**Comment by fooblahblah** [comment]
Here's a different example:

"POST should store alias correctly" in {
      val alias = JObject(JField("aliasId", JString("test")) :: JField("target", JString("http://localhost")) :: Nil)

```
  path$("/aliases") {
    post$(JValueToByteArray(alias)) { response: HttpResponse[Array[Byte]] =>
      response.status.code mustEqual(OK)
    } ~
    get$ {  response: HttpResponse[Array[Byte]] =>
      println("This line does not print")
      response.status.code mustEqual(OK)
      response.content.map(ByteArrayToJValue(_)) mustEqual(Some(List("test1")))
    }
  } should "return OK"
}
```

**Comment by jdegoes** [comment]
Fixed in HEAD.
