### ISSUE TITLE
Support for Scala 2.9.2, 2.9.3 or 2.10.1

### ISSUE THREAD

**Issue by katragadda** [jdegoes/blueeyes#104]
Looks like there blueeyes doesn't support newer scala version yet. I get below warnings and unresolved dependency error. Any idea when it would be? Also, is it really hard to keep up new versions. Thanks.

[warn]  :: com.github.jdegoes#blueeyes-core_2.9.3;0.6.0: not found
[warn]  :: com.github.jdegoes#blueeyes-mongo_2.9.3;0.6.0: not found
[warn]  :: com.github.jdegoes#blueeyes-json_2.9.3;0.6.0: not found

**Comment by noelwelsh** [comment]
Try 0.6.1-SNAPSHOT. It is compiled for 2.9.1 and 2.9.2.

**Comment by noelwelsh** [comment]
It's now compiled for 2.9.3 as well.
