### ISSUE TITLE
?/ RestPathPattern at the end of the combinator chain only matches / variation of URI

### ISSUE THREAD

**Issue by fooblahblah** [jdegoes/blueeyes#14]
If I have RestPathPattern's in my service which are not at the end of the sequence of combinators it functions  correctly.  E.g. /foo or /foo/ both work.

If the /? variation occurs as the last entries in the chain it only matches /foo/.

A more complete example snippet (psuedo-code):

service prelude.... {
  path("/foo") {
    ....
  } ~
  path("/blah" /?) {
    .... // this works as either /blah or /blah/
  } ~
  path("/baz") {
    ....
  } ~ 
  path("/fooblahblah" /?) {
    .... // Only works in the /fooblahblah/ variant unless I move it up before /baz
  } 
}

When I say "does not work" it's actually a 404 response.

**Comment by mlagutko** [comment]
I created a small service based on your example:

path("/foo") {
            get { request: HttpRequest[ByteChunk] =>
                Future.sync(HttpResponse[ByteChunk]())
            }
} ~
path("/blah" /?) {
  get { request: HttpRequest[ByteChunk] =>
      Future.sync(HttpResponse[ByteChunk]())
  }
} ~
path("/baz") {
  get { request: HttpRequest[ByteChunk] =>
      Future.sync(HttpResponse[ByteChunk]())
  }
} ~
path("/fooblahblah" /?) {
  get { request: HttpRequest[ByteChunk] =>
      Future.sync(HttpResponse[ByteChunk]())
  }
}

The service works for both the "/fooblahblah/" and the "/fooblahblah". Looks like there is another reason. A complete service will be helpful to find a reason.

**Comment by fooblahblah** [comment]
If you go in the LS services repo, check out the refcode service. That is the one I had to reorder the paths to make work (or fail).

**Comment by mlagutko** [comment]
RefcodeService has the following services:
path("/'id") {
 ...
}

and

path("/countries" /?) {
...
}

when we put "countries" service after "'id" service then the request "service.get("/countries")" is handled by "'id" service of course and this service return NOT_FOUND error.   But if we put "countries" service before "'id" service then everything works fine.

So the original problem is that more then one service can handle the same request. As a result we get an unexpected request.

**Comment by fooblahblah** [comment]
I'm not clear on how this is not a bug?  I thought /? Simple made the trailing / optional?  How do /'id and /countries/? interact?  Guess I don't understand symbol patterns or /?  :)

**Comment by mlagutko** [comment]
/? does not relate to the problem.

The Symbol RestPathPattern is pattern which is defined by a symbol like 'id. Any request which contains ONE word matches the symbol pattern. That mean request "/countries" matches the pattern 'id. When the pattern 'id is defined before the pattern /countries then the service 'id handles the request ''/countries". That is the problem. So the main problem is that wrong service ('id service) handles the request. In this situation the only solution is to include /countries service before 'id service like you have done.

**Comment by fooblahblah** [comment]
Ah, that makes sense now.  Thanks for the additional description!
