### ISSUE TITLE
JPath nested syntax returns JNothing

### ISSUE THREAD

**Issue by fooblahblah** [jdegoes/blueeyes#15]
Maybe I'm doing something wrong, but subpath syntax does not appear to work.  Note the last example does work if one drills in manually:

scala> val j = JObject(JField("A", JObject(JField("id", JString("X")) :: JField("description", JString("")) :: Nil)) :: Nil)
j: blueeyes.json.JsonAST.JObject = JObject(List(JField(A,JObject(List(JField(id,JString(X)), JField(description,JString()))))))

scala> j \ ".A.id"
res17: blueeyes.json.JsonAST.JValue = JNothing

scala> j \ "A.id"
res17: blueeyes.json.JsonAST.JValue = JNothing

scala> j.flattenWithPath
res19: List[(blueeyes.json.JPath, blueeyes.json.JsonAST.JValue)] = List((.A.id,JString(X)), (.A.description,JString()))

scala> j \ "A" \ "id"
res20: blueeyes.json.JsonAST.JValue = JString(X)

**Comment by fooblahblah** [comment]
Maybe I'm missing JPath implicits?  :)  Will try...

**Comment by fooblahblah** [comment]
The following work:

scala> j(JPath(".A.id"))
res27: blueeyes.json.JsonAST.JValue = JString(X)

scala> j(JPath("A.id"))
res28: blueeyes.json.JsonAST.JValue = JString(X)

**Comment by jdegoes** [comment]
The "\" method is designed to look only at immediate children.

The functionality you want can be accessed via the "get" method, e.g.:

j.get(".A.id")

**Comment by fooblahblah** [comment]
Ok, thanks.  I'm using apply for now.
