### ISSUE TITLE
Release com.github.blueeyes/blueeyes jars (or update the README)

### ISSUE THREAD

**Issue by michaelklishin** [jdegoes/blueeyes#17]
Looks like either artifacts mentioned in the README were never released or group/org name is incorrect (doesn't seem to be in sync with the SBT file). It is not a show stopper but makes getting started a lot more painful: cloning the repo, building jars, figuring out how to hook them up with SBT 0.10 or how to use a local Ivy repository.

My suggestion is to begin releasing artifacts at least once a week. Snapshots are fine, of course.

**Comment by mlagutko** [comment]
README is updated.
