### ISSUE TITLE
Exception thrown inside http request hander combinator partials are not logged

### ISSUE THREAD

**Issue by fooblahblah** [jdegoes/blueeyes#2]
A recent change is suppressing logging of exceptions which occur inside the HttpRequestHandlerCombinator partials (i.e. the innermost code inside the combinators).  The client response does in fact show the stack trace, so it's probably a minor tweak.  This occurs when the service is running via the HttpServer (haven't determined if unit tests do the same).

**Comment by jdegoes** [comment]
It was poor practice to log directly in the netty engine because there was no way to turn it off. Probably, I will change the logging combinator so that by default it will log the death of all futures. This way those errors can be turned on or off on a per service basis.
