### ISSUE TITLE
Server shutdown takes almost 2 minutes

### ISSUE THREAD

**Issue by jamesward** [jdegoes/blueeyes#23]
When I shutdown the server my cpu is pegged and it takes almost 2 minutes to stop:
INF [20111010-09:36:58.396] blueeyes: Server stopped
INF [20111010-09:38:44.244] blueeyes: Netty engine is stopped

I'm on Linux and have tried BlueEyes 0.4.24 and 0.4.26.  Here is a little sample project that I used to test with:
https://github.com/jamesward/helloblueeyes

I did notice that if I make a request in my browser while it's shutting down then the shutdown happens.  So maybe Netty is waiting for an open connection to close or something.

**Comment by jdegoes** [comment]
The server shutdown will wait until connections are terminated or timed out. Probably, the length of a time out during shutdown should be configurable so developers can choose during testing to make it 0 (terminate instantly).

**Comment by jamesward** [comment]
That would be nice.  But the weird thing is how modern browsers hold connections open even after the page has loaded.  So if you load a page from blueeyes in a browser then try to shutdown, blueeyes waits even though there really isn't anything happening on the connection.  I wonder if there is some way to know the difference between an idle connection being held open by the browser and one that is actually in use.

**Comment by mlagutko** [comment]
Fixed.
