### ISSUE TITLE
Health uri exhibits high load

### ISSUE THREAD

**Issue by fooblahblah** [jdegoes/blueeyes#24]
I have a simple service I use to measure performance changes to different BlueEyes updates.  After running 1M requests through a service with a simple GET handler, I see the health requests generate up to 80% CPU load and take quite a long time to return (avg 2.5 secs).  This is ironic since it causes load by our monitoring in production.

``` scala
trait BenchmarkService extends BlueEyesServiceBuilder with HttpRequestHandlerCombinators with HttpRequestCombinators with BijectionsChunkJson with BijectionsChunkByteArray with ServiceVersion {
  private val _logger = Logger.get

  val benchmarkService = service("benchmark", serviceVersion) {
    healthMonitor { monitor =>
      requestLogging { context =>
        request {
          path("/ping") {
            produce(application/json) {
              get { request: HttpRequest[ByteChunk] =>
                HttpResponse[JValue](content = Some(JString("pong"))).future
              }
            }
          }
        }
      }
    }
  }
}
```

Hitting http://localhost:8080/blueeyes/services/benchmark/v1/health  will generate the high load.

**Comment by fooblahblah** [comment]
BTW, we're using commit 237cf67c19e283364509827d13dca8e3c8454496

**Comment by jdegoes** [comment]
Misha's working on an incremental way of doing histograms which will eliminate this performance problem.

**Comment by mlagutko** [comment]
fixed
