### ISSUE TITLE
produces(application/json) vs produce(application/json)

### ISSUE THREAD

**Issue by mslinn** [jdegoes/blueeyes#25]
The readme shows a line of code, which does not compile:
produces(application/json)

Should not the code should actually be:
produce(application/json)

**Comment by mslinn** [comment]
Sorry, was using an old version of blueeyes

**Comment by jdegoes** [comment]
Thanks, Mike, we'll fix that!

Regards,

John A. De Goes
Twitter: @jdegoes 
LinkedIn: http://linkedin.com/in/jdegoes

**Comment by mslinn** [comment]
Hey John,

Thanks for getting back to me so quickly but this is not a bug; the DSL changed in a recent update so your docs and the code are in sync. Apologies for the false alarm.

James Ward and I are working with blueeyes on a small project together. We sorely wanted to chat with someone about the code via Google Plus, Skype or whatever. Can you spare a few minutes some afternoon?

Mike

**Comment by jdegoes** [comment]
Sure, love to chat. My Skype id is "jdegoes", Kris' id is "nuttycom", and Misha's id is "mlagutko". We're the primary committers to the project. Just ping us anytime.

Regards,

John A. De Goes
Twitter: @jdegoes 
LinkedIn: http://linkedin.com/in/jdegoes

**Comment by mslinn** [comment]
John,

You can see our little project here: 
https://github.com/jamesward/helloblueeyes 
https://github.com/jamesward/helloblueeyes/blob/master/src/main/scala/HelloJsonServices.scala

I'm trying to get request logging enabled. I looked at your code example 
https://github.com/jdegoes/blueeyes:

trait  RequestLogDemo  extends  BlueEyesServiceBuilder  {
   val  requestLogDemoService  =  service("requestlogdemo",  "1.32")  {
     requestLogging  {
       context  =>
         startup  {
           request  {  state  =>
             path("/foo")  {
               contentType(application/json)  {
                 get  {  request  =>
                   ...
                 }
               }
             }
           }
         }
     }
   }
}

Questions:
1. Is the startup block the same as the service startup, or a different
   startup? How could I discover this for myself?
2. I guessed that the requestLogging startup block is separate for the
   service startup because I see same contents as the service main
   body. Below is my attempt to include request logging as well as
   log.info output. Some compilation errors follow that stump me.
3. Where does the request log information go? I see the call on the SBT
   console but I don't see a file created

import blueeyes._
import blueeyes.concurrent.Future
import blueeyes.core.data.{BijectionsChunkJson, BijectionsChunkString, 
ByteChunk}
import blueeyes.core.http.{HttpRequest, HttpResponse}
import blueeyes.core.http.combinators.HttpRequestCombinators
import blueeyes.core.service.{HttpService, HttpServiceContext}
import blueeyes.json.JsonAST._
import blueeyes.json.xschema.codegen.State

trait HelloJsonServices extends BlueEyesServiceBuilder
with HttpRequestCombinators
with BijectionsChunkString
with BijectionsChunkJson {
   val helloJson: HttpService[ByteChunk] = service("helloJson", "0.1") {
     requestLogging { context  =>
       logging { log =>
         startup {
           request { state =>
             path("/json") {
               jvalue {
                 get {
                   requestParam: HttpRequest[JValue] =>
                     val json = JString("Hello World!")
                     val response = HttpResponse[JValue](content = 
Some%28json%29)
                     log.info(response.toString())
                     Future.sync(response)
                 }
               }
             }
           }
         }
       }
     }
   }
}

Compiling 2 Scala sources to 
E:\work\experiments\scala\helloblueeyes\target\scala-2.9.1\classes...
[error] 
E:\work\experiments\scala\helloblueeyes\src\main\scala\HelloJsonServices.scala:18: 
missing parameter type
[error]           request { state =>
[error]                     ^
[error] 
E:\work\experiments\scala\helloblueeyes\src\main\scala\HelloJsonServices.scala:16: 
polymorphic expression cannot be instantiated to expected type;
[error]  found   : [T, S]blueeyes.core.service.HttpServiceContext => 
blueeyes.core.service.HttpServiceDescriptor[T,S]
[error]  required: 
blueeyes.core.service.HttpServiceDescriptor[blueeyes.core.data.package.ByteChunk,?]
[error]       logging { log =>
[error]               ^
[error] two errors found

Thanks!

Mike

**Comment by mslinn** [comment]
Should have shown this code, which has service startup and shutdown blocks.

import blueeyes._
import blueeyes.concurrent.Future
import blueeyes.core.data.{BijectionsChunkJson, BijectionsChunkString, 
ByteChunk}
import blueeyes.core.http.{HttpRequest, HttpResponse}
import blueeyes.core.http.combinators.HttpRequestCombinators
import blueeyes.core.service.{HttpService, HttpServiceContext}
import blueeyes.json.JsonAST._
import blueeyes.json.xschema.codegen.State

trait HelloJsonServices extends BlueEyesServiceBuilder
with HttpRequestCombinators
with BijectionsChunkString
with BijectionsChunkJson {
   val helloJson: HttpService[ByteChunk] = service("helloJson", "0.1") {
     startup {
       println("startup") // want to use logger here
       Future.sync(())
     } ->
     requestLogging { context  =>
       logging { log =>
         startup {
           request { state =>
             path("/json") {
               jvalue {
                 get {
                   requestParam: HttpRequest[JValue] =>
                     val json = JString("Hello World!")
                     val response = HttpResponse[JValue](content = 
Some%28json%29)
                     log.info(response.toString())
                     Future.sync(response)
                 }
               }
             }
           }
         }
       }
     } ->
     shutdown {
       println("shutdown") // want to use logger here
       Future.sync(())
     }
   }
}

Mike

John,

You can see our little project here: 
https://github.com/jamesward/helloblueeyes 
https://github.com/jamesward/helloblueeyes/blob/master/src/main/scala/HelloJsonServices.scala

I'm trying to get request logging enabled. I looked at your code example 
https://github.com/jdegoes/blueeyes:

trait  RequestLogDemo  extends  BlueEyesServiceBuilder  {
   val  requestLogDemoService  =  service("requestlogdemo",  "1.32")  {
     requestLogging  {
       context  =>
         startup  {
           request  {  state  =>
             path("/foo")  {
               contentType(application/
json)  {
                 get  {  request  =>
                   ...
                 }
               }
             }
           }
         }
     }
   }
}

Questions:
1. Is the startup block the same as the service startup, or a different
   startup? How could I discover this for myself?
2. I guessed that the requestLogging startup block is separate for the
   service startup because I see same contents as the service main
   body. Below is my attempt to include request logging as well as
   log.info output. Some compilation errors follow that stump me.
3. Where does the request log information go? I see the call on the SBT
   console but I don't see a file created

import blueeyes._
import blueeyes.concurrent.Future
import blueeyes.core.data.{BijectionsChunkJson, BijectionsChunkString, 
ByteChunk}
import blueeyes.core.http.{HttpRequest, HttpResponse}
import blueeyes.core.http.combinators.HttpRequestCombinators
import blueeyes.core.service.{HttpService, HttpServiceContext}
import blueeyes.json.JsonAST._
import blueeyes.json.xschema.codegen.State

trait HelloJsonServices extends BlueEyesServiceBuilder
with HttpRequestCombinators
with BijectionsChunkString
with BijectionsChunkJson {
   val helloJson: HttpService[ByteChunk] = service("helloJson", "0.1") {
     requestLogging { context  =>
       logging { log =>
         startup {
           request { state =>
             path("/json") {
               jvalue {
                 get {
                   requestParam: HttpRequest[JValue] =>
                     val json = JString("Hello World!")
                     val response = HttpResponse[JValue](content = 
Some%28json%29)
                     log.info(response.toString())
                     Future.sync(response)
                 }
               }
             }
           }
         }
       }
     }
   }
}

Compiling 2 Scala sources to 
E:\work\experiments\scala\helloblueeyes\target\scala-2.9.1\classes...
[error] 
E:\work\experiments\scala\helloblueeyes\src\main\scala\HelloJsonServices.scala:18: 
missing parameter type
[error]           request { state =>
[error]                     ^
[error] 
E:\work\experiments\scala\helloblueeyes\src\main\scala\HelloJsonServices.scala:16: 
polymorphic expression cannot be instantiated to expected type;
[error]  found   : [T, S]blueeyes.core.service.HttpServiceContext => 
blueeyes.core.service.HttpServiceDescriptor[T,S]
[error]  required: 
blueeyes.core.service.HttpServiceDescriptor[blueeyes.core.data.package.ByteChunk,?]
[error]       logging { log =>
[error]               ^
[error] two errors found

Thanks!

Mike

**Comment by jdegoes** [comment]
The code on the website is bogus. The combinator does not affect the startup / request / shutdown cycle. You just wrap at the top level, e.g.:

service("foo", "1.2") {
  requestLogging { context =>
    startup {  } -> request {  } -> shutdown {  }
  }
}

Sorry for the confusion. :)

Regards,

John A. De Goes
Twitter: @jdegoes 
LinkedIn: http://linkedin.com/in/jdegoes
