### ISSUE TITLE
Namespace composite servers using service name

### ISSUE THREAD

**Issue by fooblahblah** [jdegoes/blueeyes#27]
I'm playing around with creating a composite server which mixes in multiple service traits as mentioned in the documentation.  I'm able to get the server running, but it appears that all the REST paths are combined between both services.

It would be nice if the service REST path patterns could be namespaced like WAR's are namespaced in Servlet containers.   By default there could be a prefix which is the name of the service and be configurable.  

So, if I compose a server of services named "a" and "b" their respective URI prefixes would be:

http://<server>:<port>/a/<rest path patterns>
http://<server>:<port>/b/<rest path patterns>

Or, am I not configuring something correctly?

**Comment by jdegoes** [comment]
You can already namespace if you mixin the "configurableRoot" combinator. It's a service descriptor factory combinator, and therefore mixed in at the same level as healthMonitor and requestLogging. This combinator will look in the config file to find a root path for the service.

**Comment by fooblahblah** [comment]
Sweet.  I'll try that.  Thanks John!
