### ISSUE TITLE
Format or example of val FileLoc = "/etc/default/blueeyes.conf"

### ISSUE THREAD

**Issue by sjcarroll6** [jdegoes/blueeyes#3]
Hi, I don't know if you accept dumb ass questions but could you provide an example of the configuration file referenced below. I'm trying out the mongodb persistence library and could not find an example or format of the file.

val FileLoc = "/etc/default/blueeyes.conf"

Best Regards

**Comment by jdegoes** [comment]
Done, see README.md or view "Source" on Github.

Essentially, the config file must contain the following:

```
mongo {
  servers: ["host1:port1", ... ]
}
```

Note that you don't have to use Guice and that we're in the process of refactoring this code to make it more DI-provider agnostic.
