### ISSUE TITLE
blueeyes.conf sample is missing

### ISSUE THREAD

**Issue by kolchanov** [jdegoes/blueeyes#30]
Please provide sample of blueeyes.conf for BlueEyesDemo.

**Comment by kolchanov** [comment]
Found in tests

services {
    contactlist {
        v1 {
            log {
                    level = "info"
                    console = true
                    use_parents = false
            }
            requestLog {
                enabled = false
            }
            mongo {
                servers    = ["localhost"]
                database   = "mydb"
                collection = "mycollection"

```
            dropBeforeStart {
                mydb = ["mycollection"]
            }
        }
    }
}
```

}

**Comment by mlagutko** [comment]
added to "blueeyes.demo" package
