### ISSUE TITLE
How to emit JSON for a class?

### ISSUE THREAD

**Issue by mslinn** [jdegoes/blueeyes#32]
I'd like to be able to convert this class into JSON so it could be assigned to a JValue:

```
case class TextMatch(val workCellRef:ActorRef, val length:Int = 0, val startPos:Int = 0, val endPos:Int = 0)
```

The JSON would look like this:

```
{
  "TextMatch": {
    "workCellRef":"opaqueStuff", "length":123, "startPos":234, "endPos":456
  }
}
```

How can I do this?

I also need to turn a list of `TextMatch` objects into JSON, perhaps something like the following. Again, how would I do that so the list could be assigned to a JValue?

```
{ 
  [
    "TextMatch": {
      "workCellRef":"opaqueStuff", "length":123, "startPos":234, "endPos":456
    },
    "TextMatch": {
      "workCellRef":"opaqueStuff", "length":123, "startPos":234, "endPos":456
    },
    "TextMatch": {
      "workCellRef":"opaqueStuff", "length":123, "startPos":234, "endPos":456
    },
  ]
}
```

Thanks,

Mike

**Comment by jdegoes** [comment]
There's no great way to do this at present (although a very nice method is coming shortly). 

For now, you can use the package blueeyes.json.xschema, which contains a notion of serialization, expressed in terms of decomposition and extraction, then write your own decomposer / extractor. Take a look at the examples in that package for more information. 

Basically, it will end up looking something like:

implicit val TextMatchDecomposer = new Decomposer[TextMatch] {
  def decompose(v: TextMatch) = JObject(
    JField("workCellRef", v.workCellRef.serialize) ::
    JField("length", v.length.serialize) :: 
    JField("startPos", v.startPos.serialize) :: 
    JField("endPos", v.endPos.serialize) :: Nil
  )

Assuming appropriate implicit decomposers/extractors are in scope for ActorRef and Int types (the latter you get for free with xschema by importing DefaultSerialization._).
