### ISSUE TITLE
scala-tools repository down

### ISSUE THREAD

**Issue by magegu** [jdegoes/blueeyes#39]
hi, 

http://nexus.scala-tools.org/content/repositories/ seem to be down: 

502 Bad Gateway

Scala-Tools.org states:
Hosting your projects on Scala-tools.org
We are no longer accepting hosting requests, sorry.

**Comment by noelwelsh** [comment]
What version of BlueEyes are you using? If it's 0.5 and above you can use the ReportGrid repo at 

  http://nexus.reportgrid.com/content/repositories/

Hopefully the ReportGrid guys will populate this repo with a 0.4 release as well.

**Comment by noelwelsh** [comment]
I haven't heard back from you, so I assume you're successfully using the ReportGrid repository.
