### ISSUE TITLE
sbt-idea-plugin 0.1-SNAPSHOT is old

### ISSUE THREAD

**Issue by bartschuller** [jdegoes/blueeyes#4]
I tried running ./sbt in a fresh clone and got

```
[error] /Users/schuller/scala/blueeyes/project/build/BlueEyesProject.scala:58: not found: type IdeaProject
```

After trying various things, the only change that works is upgrading to the current non-SNAPSHOT version of sbt-idea-plugin. In _project/plugins/Plugins.scala_:

```
val sbtIdea = "com.github.mpeltonen" % "sbt-idea-plugin" % "0.2.0"
```

**Comment by jdegoes** [comment]
Thanks, fixed in head!
