### ISSUE TITLE
Update to latest akka version (2.0-RC2)

### ISSUE THREAD

**Issue by cdedie** [jdegoes/blueeyes#41]
Can you please update the blueeyes akka dependency to the latest akka version (2.0-RC2).

**Comment by noelwelsh** [comment]
RC3 was released today, so this might make your request out of date. Do you need RC2 specifically, or just something more recent than the 2.0-M3 version the current master branch builds against? (I'm assuming you're using the 0.6 SNAPSHOTS, but you may need to clarify which BlueEyes version you're referring to.)

**Comment by cdedie** [comment]
Yes we are using the 0.6 Snapshot version. The akka RC3 release would be perfect.

**Comment by noelwelsh** [comment]
Akka 2 has been released, showing the benefits of laziness. Realistically, I won't have time to do this for about a fortnight and I expect the ReportGrid guys are busy supporting their new product. If you open a pull request with the changes (there are 3 build.sbt files you need to update, IIRC, then run the tests) I'll merge it in.

**Comment by noelwelsh** [comment]
I've committed the change to master. Hopefully someone at ReportGrid will make a new snapshot release.
