### ISSUE TITLE
Turn on issue tracking for spray-can

### ISSUE THREAD

**Issue by astubbs** [jdegoes/blueeyes#44]
Wanted to add an issue to get M1 release in a repo somewhere, but it seems issue tracking for spray-can's github page is off?

**Comment by astubbs** [comment]
omg that was hard to find:
http://repo.spray.cc/cc/spray/spray-can/1.0-M1/

Ended up finding the publish to setting in the build file. Can that get put somewhere on the front page?

**Comment by astubbs** [comment]
Ok, don't know why that was hard to find - https://github.com/spray/spray/issues must have been looking at a fork or something weird..

**Comment by noelwelsh** [comment]
Hi Antony,

Is this in the correct place? I'm a bit confused as to whether meant
to send this to the Spray guys, or if you're asking for a change to
Blueeyes.

Cheers,
N.

On Mon, Apr 9, 2012 at 9:17 PM, Antony Stubbs
reply@reply.github.com
wrote:

**Comment by astubbs** [comment]
Yes, it's the wrong place, but I thought they were turned off, and was trying to contact them through you. You can ignore all this rubbish ;)

**Comment by noelwelsh** [comment]
No problemo.
