### ISSUE TITLE
mocking mongodb

### ISSUE THREAD

**Issue by michaelmosmann** [jdegoes/blueeyes#48]
Is there any chance to isolate your mongodb mocking stuff in an extra project? I have a project which starts a real mongodb instance for junit tests, but mocking would be fine.

https://github.com/flapdoodle-oss/embedmongo.flapdoodle.de

**Comment by noelwelsh** [comment]
I don't really understand what you're asking. The mongo stuff all lives in its own subtree: https://github.com/jdegoes/blueeyes/tree/master/mongo Is that what you're looking for?

**Comment by michaelmosmann** [comment]
yes:)
