### ISSUE TITLE
Dependency Resolve Problem

### ISSUE THREAD

**Issue by cheeseng** [jdegoes/blueeyes#49]
I have the following resolve problem when trying to compile the source via sbt compile:-

[warn]  [NOT FOUND  ] org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit (1694ms)
[warn] ==== Sonatype Jetty: tried
[warn]   https://oss.sonatype.org/content/groups/jetty/org/eclipse/jetty/orbit/javax.servlet/3.0.0.v201112011016/javax.servlet-3.0.0.v201112011016.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] {file:/home/cheeseng/git/blueeyes/}core/*:update: sbt.ResolveException: download failed: org.eclipse.jetty.orbit#javax.servlet;3.0.0.v201112011016!javax.servlet.orbit

What can I do to rectify the problem?

Thanks!

**Comment by dchenbecker** [comment]
A fix will be in shortly

**Comment by dchenbecker** [comment]
Fixed in 98ab2fedc285e2dc9d4ac45a624f9e569b43b90b
