### ISSUE TITLE
Configgy conf file errors

### ISSUE THREAD

**Issue by sjcarroll6** [jdegoes/blueeyes#5]
The following conf file fails as noted below. I tried many variants but none would work.  

mongo {
  servers: ["localhost:27017"]
}

CRI [20110118-19:50:53.967] configgy: Failed to load config file 'C:\dev\test05/C:\dev\test05\blueeyes.conf'
CRI [20110118-19:50:53.967] configgy: net.lag.configgy.ParseException: [3.10] failure: `{' expected but`:' found

  servers: ["localhost:27017"]

**Comment by sjcarroll6** [comment]
Figured it out the : should have been an =

**Comment by jdegoes** [comment]
Sorry, I confuse Configgy's style with JSON sometimes. They're SO close...
