### ISSUE TITLE
NoClassDefFoundError: blueeyes.bkka.AkkaDefaults$

### ISSUE THREAD

**Issue by cheeseng** [jdegoes/blueeyes#50]
I am having the following error when running sbt test:-

[error] Could not create an instance of blueeyes.persistence.mongo.MongoSpec
[error]   caused by java.lang.NoClassDefFoundError: Could not initialize class blueeyes.bkka.AkkaDefaults$
[error]   blueeyes.bkka.AkkaDefaults$class.defaultFutureDispatch(FutureDispatch.scala:9)
[error]   blueeyes.persistence.mongo.mock.MockMongo.defaultFutureDispatch(MockMongoImplementation.scala:23)
[error]   blueeyes.persistence.mongo.mock.MockMongo$$anonfun$database$1.apply(MockMongoImplementation.scala:27)
[error]   blueeyes.persistence.mongo.mock.MockMongo$$anonfun$database$1.apply(MockMongoImplementation.scala:26)
[error]   scala.Option.getOrElse(Option.scala:108)
[error]   blueeyes.persistence.mongo.mock.MockMongo.database(MockMongoImplementation.scala:26)
[error]   blueeyes.persistence.mongo.MongoSpec.<init>(MongoSpec.scala:28)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:513)
[error]   org.specs2.reflect.Classes$class.createInstanceFor(Classes.scala:131)
[error]   org.specs2.reflect.Classes$.createInstanceFor(Classes.scala:178)
[error]   org.specs2.reflect.Classes$$anonfun$createInstanceOfEither$1.apply(Classes.scala:121)
[error]   org.specs2.reflect.Classes$$anonfun$createInstanceOfEither$1.apply(Classes.scala:121)
[error]   scala.Option.map(Option.scala:133)
[error]   org.specs2.reflect.Classes$class.createInstanceOfEither(Classes.scala:121)
[error]   org.specs2.reflect.Classes$.createInstanceOfEither(Classes.scala:178)
[error]   org.specs2.reflect.Classes$class.tryToCreateObjectEither(Classes.scala:95)
[error]   org.specs2.reflect.Classes$.tryToCreateObjectEither(Classes.scala:178)
[error]   org.specs2.specification.SpecificationStructure$$anonfun$createSpecificationEither$2.apply(BaseSpecification.scala:100)
[error]   org.specs2.specification.SpecificationStructure$$anonfun$createSpecificationEither$2.apply(BaseSpecification.scala:100)
[error]   scala.Option.getOrElse(Option.scala:108)
[error]   org.specs2.specification.SpecificationStructure$.createSpecificationEither(BaseSpecification.scala:100)
[error]   org.specs2.runner.TestInterfaceRunner.runSpecification(TestInterfaceRunner.scala:53)
[error]   org.specs2.runner.TestInterfaceRunner.run(TestInterfaceRunner.scala:48)
[error]   sbt.TestRunner.delegateRun(TestFramework.scala:62)
[error]   sbt.TestRunner.run(TestFramework.scala:56)
[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
[error]   sbt.TestRunner.run(TestFramework.scala:85)
[error]   sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
[error]   sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:184)
[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:196)
[error]   sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
[error]   sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:184)
[error]   sbt.Tests$$anonfun$makeSerial$1$$anonfun$apply$8.apply(Tests.scala:115)
[error]   sbt.Tests$$anonfun$makeSerial$1$$anonfun$apply$8.apply(Tests.scala:115)
[error]   scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
[error]   scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
[error]   scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
[error]   scala.collection.immutable.List.foreach(List.scala:45)
[error]   scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
[error]   scala.collection.immutable.List.map(List.scala:45)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:115)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:115)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
[error]   sbt.std.Transform$$anon$5.work(System.scala:67)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[error]   sbt.Execute.work(Execute.scala:227)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
[error]   sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
[error]   java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:138)
[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
[error]   java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:138)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[error]   java.lang.Thread.run(Thread.java:662)

Can't find the source of blueeyes.bkka.AkkaDefaults$, is it a missing source file?

**Comment by noelwelsh** [comment]
I compiled BlueEyes yesterday and didn't see this issue. Can you please
- Clean everything: sbt clean
- Remove your .ivy2 cache. I recommend you take off and nuke it from orbit. It's the only way to be sure. But if you can't achieve escape velocity rm -fr ~/.ivy2 should do it

Then try recompiling. If you still get this error I'll investigate.

**Comment by cheeseng** [comment]
Hi Noel,

It does solve the problem, thanks!

Best Regards,
Chee Seng

On Fri, Jul 6, 2012 at 8:28 PM, Noel Welsh <
reply@reply.github.com

**Comment by noelwelsh** [comment]
Good to hear!
N.
