### ISSUE TITLE
parameter combinator not working

### ISSUE THREAD

**Issue by zhanggl** [jdegoes/blueeyes#51]
I have the following code snippet 

produce(application/json){
              path("/query/mp3download/'mobileNo"){
                parameter('mobileNo){   mobileNo=>
                    get{    request:HttpRequest[ByteChunk] =>

and i get a 

> curl -i http://127.0.0.1:8080/logger/query/mp3download/1004
> HTTP/1.1 400 Expected to find value for 'mobileNo

in HttpRequestHandlerCombinators.scala i see:

  def path[T, S](path: RestPathPattern) = (h: HttpRequestHandler2[T, S]) => new HttpRequestHandler2[T, S] {
    def isDefinedAt(r: HttpRequest[T]): Boolean = path.isDefinedAt(r.subpath) && h.isDefinedAt(path.shift(r))

```
def apply(r: HttpRequest[T]): Future[HttpResponse[S]] = {
  val pathParameters = path(r.subpath).map(parameter => (parameter._1, decode(parameter._2, "UTF-8")))

  val shiftedRequest = path.shift(r)

  h(shiftedRequest.copy(parameters = shiftedRequest.parameters ++ pathParameters))
}
```

  }

the method isDefinedAt  may not have the "parameters " passed in.

please correct me if I'm missing something.

**Comment by noelwelsh** [comment]
I think the parameter combinator is broken. Simplest thing is to get the parameters out of the request.

This looks like BlueEyes 0.4, which is fairly old these days. Try upgrading to 0.6 SNAPSHOT.
