### ISSUE TITLE
What Scala JSON library do you use?

### ISSUE THREAD

**Issue by sjcarroll6** [jdegoes/blueeyes#6]
What Scala JSON library do you use?

**Comment by jdegoes** [comment]
BlueEyes uses an enhanced version of Lift-JSON (I am a committer on Lift and responsible for many improvements to Lift-JSON). Although the two share a common ancestor, they have diverged and will probably remain separate projects.

BlueEyes JSON has features like this:

jvalue.get(".foo.bar[123]")

or even:

jvalue.get("./foo|bar/.blah")

jvalue.replace("./foo|bar/.blah", JInt(1))

Among other new features.
