### ISSUE TITLE
Module not found when adding blueeyes as sbt dependencies

### ISSUE THREAD

**Issue by mariosangiorgio** [jdegoes/blueeyes#72]
I just copied the resolvers and the dependency you posted on the readme but this is the output I'm getting:

```
[info] Resolving com.reportgrid#blueeyes_2.9.2;0.6 ...
[warn]  module not found: com.reportgrid#blueeyes_2.9.2;0.6
[warn] ==== local: tried
[warn]   /Users/mariosangiorgio/.ivy2/local/com.reportgrid/blueeyes_2.9.2/0.6/ivys/ivy.xml
[warn] ==== Sonatype: tried
[warn]   http://nexus.scala-tools.org/content/repositories/public/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[warn] ==== Scala Tools: tried
[warn]   http://scala-tools.org/repo-snapshots/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[warn] ==== JBoss: tried
[warn]   http://repository.jboss.org/nexus/content/groups/public/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[warn] ==== Akka: tried
[warn]   http://repo.akka.io/releases/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[warn] ==== GuiceyFruit: tried
[warn]   http://guiceyfruit.googlecode.com/svn/repo/releases/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/com/reportgrid/blueeyes_2.9.2/0.6/blueeyes_2.9.2-0.6.pom
[info] Resolving org.scalatest#scalatest_2.9.0;1.7.2 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.reportgrid#blueeyes_2.9.2;0.6: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by noelwelsh** [comment]
I think I didn't build for 2.9.2 (which is a bit surprising -- I thought
the build was setup to do that automatically). Try hardcoding the Scala
version to 2.9.1.

Let me know if you can't get it working.

Cheers,
Noel

**Comment by mariosangiorgio** [comment]
Unfortunately I cannot resolve neither blueeyes_2.9.1.
Am I missing to include any resolver? I just copied and pasted the list you included in the readme file.

**Comment by davegurnell** [comment]
This is a guess, but I think you need to specify the version as "0.6.0" instead of "0.6".

-- Dave

**Comment by mariosangiorgio** [comment]
Nope, even that is ineffective.

**Comment by noelwelsh** [comment]
I'm on the road at the moment. I'll be back tomorrow, when I'll take a look
at the build process.

N.

**Comment by romansky** [comment]
Any updates??

**Comment by noelwelsh** [comment]
Ok, I see the problem now. The README is out of date. Correct lines are below. I'll update the README later today.

From http://noelwelsh.com/blueeyes/setup.html

resolvers ++= Seq(
  "Sonatype" at "http://oss.sonatype.org/content/repositories/public",
  "Typesafe" at "http://repo.typesafe.com/typesafe/releases/"
)

libraryDependencies ++= Seq(
  "com.github.jdegoes" %% "blueeyes-core"  % "0.6.0",
  "com.github.jdegoes" %% "blueeyes-mongo" % "0.6.0",
  "com.github.jdegoes" %% "blueeyes-json"  % "0.6.0",
  "ch.qos.logback" % "logback-classic" % "1.0.0" % "runtime"
)

**Comment by mariosangiorgio** [comment]
I confirm it works. Thanks!

**Comment by noelwelsh** [comment]
Great! I've updated the README.
