### ISSUE TITLE
shutdown hook should run after HTTP connection closes

### ISSUE THREAD

**Issue by drummond-scoreloop** [jdegoes/blueeyes#74]
It seems the http connection is still alive when the blueeyes shutdown handler is run, causing problems with upstream connections that expect the HTTP connection to continue serving requests while internal database handles are being closed.  Our loadbalancer would otherwise simply round-robin to the next available server if the connection were properly closed.

This is easily determined by adding a never ending block to the shutdown hook and connecting to the server using netcat.

The current (undesirable) workaround that we are using is to have a static initializer and override HttpServer with our own custom shutdownHook.

**Comment by noelwelsh** [comment]
I presume you're using 0.6. Can you create a pull request? That would help considerably in getting this change in. Start from the 0.6.x branch.
